### ISSUE TITLE
Legg til manglende NFK-farger i design systemet

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/design-system#32]
Etter oppdatering av design systemet (#30), mangler der en del tema-farger for NFK. Det gjelder 4 "accent" farger, og 5 "interactive"-fargesett. Alle disse ligger inne som #FFFFFF nå.

## Design systemet nå, AtB vs NFK

![collage](https://user-images.githubusercontent.com/1774972/164449677-d202cc8b-3d53-40c0-aa57-37e93065ca2c.png)

## Fra AtB Figma

<img width="878" alt="Screenshot 2022-04-21 at 13 33 33" src="https://user-images.githubusercontent.com/1774972/164450260-08515c57-d617-4b89-9210-8f20b11d2a14.png">

![Screenshot 2022-04-21 at 10 35 23](https://user-images.githubusercontent.com/1774972/164450282-a366419d-8cd4-4210-8a26-87e7c2326332.png)

**Comment by toretefre** [comment]
NFK sin designer Anete ser på dette mandag 19. september. Tore legger da inn farger i design-systemet onsdag 21. september.

**Comment by mikaelbr** [comment]
Denne er ferdig @toretefre ?

**Comment by toretefre** [comment]
Yes
